### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by syyyr** [LithApp/Lith#26]
Consistent. Just open and close the app
```asan
$ ./Lith 
Connecting
Connected!
=== RESET
There is 0 orphan lines
There is 0 hotlist items
qrc:/NickList.qml:43: TypeError: Cannot read property 'title' of null

=================================================================
==207878==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x556d31bdd352 in realloc (/home/vk/git/Lith/build/Lith+0x167352)
    #1 0x7fde5088369b  (/usr/lib/dri/radeonsi_dri.so+0x5c669b)

Indirect leak of 160 byte(s) in 1 object(s) allocated from:
    #0 0x556d31bdcfc9 in malloc (/home/vk/git/Lith/build/Lith+0x166fc9)
    #1 0x7fde5c826595 in QObjectPrivate::addConnection(int, QObjectPrivate::Connection*) (/usr/lib/libQt5Core.so.5+0x2dd595)

Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x556d31c12739 in operator new(unsigned long) (/home/vk/git/Lith/build/Lith+0x19c739)
    #1 0x7fde5c832745 in QObject::QObject(QObject*) (/usr/lib/libQt5Core.so.5+0x2e9745)
    #2 0x556d31c428a3 in main (/home/vk/git/Lith/build/Lith+0x1cc8a3)
    #3 0x7fde5bfb0151 in __libc_start_main (/usr/lib/libc.so.6+0x28151)

Indirect leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x556d31c12739 in operator new(unsigned long) (/home/vk/git/Lith/build/Lith+0x19c739)
    #1 0x7fde5c82a927 in QObjectPrivate::connectImpl(QObject const*, int, QObject const*, void**, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, int const*, QMetaObject const*) (/usr/lib/libQt5Core.so.5+0x2e1927)

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x556d31c12739 in operator new(unsigned long) (/home/vk/git/Lith/build/Lith+0x19c739)
    #1 0x7fde5c8263b7 in QObjectPrivate::addConnection(int, QObjectPrivate::Connection*) (/usr/lib/libQt5Core.so.5+0x2dd3b7)

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x556d31c12739 in operator new(unsigned long) (/home/vk/git/Lith/build/Lith+0x19c739)
    #1 0x556d31c4288c in main (/home/vk/git/Lith/build/Lith+0x1cc88c)
    #2 0x7fde5bfb0151 in __libc_start_main (/usr/lib/libc.so.6+0x28151)

SUMMARY: AddressSanitizer: 656 byte(s) leaked in 6 allocation(s).
```

**Comment by MartinBriza** [comment]
I ran multiple memory analysis tools on Lith in the past few months and I found some leaks but nothing major, really.  I don't think it makes sense to keep this issue open now when I think there's (well, I hope) nothing to worry about in this regard.
